name: CI
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                    python-version: '3.12'
            - run: pip install pytest pandas boto3
            - run: pytest tests/ -v

    terraform:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: hashicorp/setup-terraform@v3
            - run: terraform fmt -check -recursive
              working-directory: infra
            - run: terraform init -backend=false
              working-directory: infra
            - run: terraform validate
              working-directory: infra
